version: 2.1
orbs:
  slack: circleci/slack@4.3.0
jobs:
  unit-tests:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - run: bundle install
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run: bundle exec fastlane scan
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  version: 2.1
  unit-tests:
    jobs:
      - unit-tests:
          context: slack
          filters:
            branches:
              only: main
