version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - run: bundle install
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run: bundle exec fastlane scan
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
        filters:
          branches:
            only:
              - main
