version: 2.1

orbs:
  slack: circleci/slack@4.3.0

executors:
  macos-executor:
    macos:
      xcode: 12.4.0

commands:
  setup:
    steps:
      - checkout
      - run: bundle install
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
  slack_notify_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  slack_notify_success:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  unit-tests:
    executor:
      name: macos-executor
    steps:
      - setup
      - run: bundle exec fastlane unit_tests
      - store_test_results:
          path: unit_test_output
      - store_artifacts:
          path: unit_test_output
          destination: scan-output
      - slack_notify_fail
  snapshot-tests:
    executor:
      name: macos-executor
    steps:
      - setup
      - run: bundle exec fastlane snapshot_tests
      - store_test_results:
          path: snapshot_test_output
      - store_artifacts:
          path: snapshot_test_output
          destination: scan-output
      - slack_notify_fail
  did-finish-jobs:
    executor:
      name: macos-executor
    steps:
      - run: echo "did finish jobs"
      - slack_notify_fail
      - slack_notify_success

workflows:
  version: 2.1
  unit-tests:
    jobs:
      - unit-tests:
          context: slack
          filters:
            branches:
              only: main
      - snapshot-tests:
          context: slack
          filters:
            branches:
              only: main
      - did-finish-jobs:
          requires:
            - unit-tests
            - snapshot-tests
          context: slack
          filters:
            branches:
              only: main