default_platform :ios

platform :ios do
  desc "Unit testing"
  lane :unit_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "ladder-client",
      device: "iPhone 8",
      only_testing: "ladder-clientTests"
    )
  end

  desc "Snapshot testing"
  lane :snapshot_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "ladder-client",
      device: "iPhone 8",
      only_testing: "ladder-clientSnapshotTests"
    )
  end

end