default_platform :ios

platform :ios do
  desc "Unit testing"
  lane :unit_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "ladder-client",
      device: "iPhone 8",
      only_testing: "ladder-clientTests"
    )
  end

  desc "Snapshot testing"
  lane :snapshot_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "ladder-client",
      device: "iPhone 8",
      only_testing: "ladder-clientSnapshotTests"
    )
  end

  desc "Upload adhoc build"
  lane :adhoc_upload do
    app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_CONNECT_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}",
      key_content: "#{ENV['APP_STORE_CONNECT_KEY_CONTENT']}",
      duration: 1200,
      in_house: false,
    )
    match(type: "adhoc", app_identifier: "org.kenzan8000.ladder-client")
    match(type: "adhoc", app_identifier: "org.kenzan8000.ladder-client.app-extension")
    gym(export_method: "ad-hoc", configuration: "adhoc", scheme: "ladder-client")
    pilot
  end

  desc "Upload beta build"
  lane :beta_upload do
    puts "#{ENV['APP_STORE_CONNECT_KEY_ID']}"
    puts "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}"
    puts "#{ENV['APP_STORE_CONNECT_KEY_CONTENT']}"
    puts "#{ENV}"
    app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_CONNECT_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}",
      key_content: "#{ENV['APP_STORE_CONNECT_KEY_CONTENT']}",
      duration: 1200,
      in_house: false,
    )
    match(type: "appstore", app_identifier: "org.kenzan8000.ladder-client")
    match(type: "appstore", app_identifier: "org.kenzan8000.ladder-client.app-extension")
    gym(export_method: "app-store", configuration: "Release", scheme: "ladder-client")
    pilot
  end
end